//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> UserFIOID { get; set; }
        public Nullable<int> UserLoginID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderDelivery { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceINOrder { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
