//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Description { get; set; }
        public string Composition { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> isDiscountActive { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
